config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'comrades', to: 'users#comrades'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comradery.rb
class Comradery < ApplicationRecord
  belongs_to :user
  belongs_to :comrade, class_name: 'User' #belongs to comrade, but the class name it's User
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  # before_action :iex_client_sandbox, only: [:new_lookup]
  def iex_client
    IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:publishable_token],
      secret_token: Rails.application.credentials.iex_client[:secret_token],
      endpoint: 'https://cloud.iexapis.com/v1'
    )
  end

  def iex_client_sandbox
    IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:publishable_token_sandbox],
      secret_token: Rails.application.credentials.iex_client[:secret_token_sandbox],
      endpoint: 'https://sandbox.iexapis.com/v1'
        )
  end

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:publishable_token_sandbox],
      secret_token: Rails.application.credentials.iex_client[:secret_token_sandbox],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
      new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => exception
      nil
    end
  end
  # private_class_method :iex_client

  Stock.where(ticker: 'GOOG').first

  def self.get_stock_from_db(ticker_symbol)
    Stock.where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :comraderies
  has_many :comrades, through: :comraderies

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.get_stock_from_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    'Anonymous'
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController


  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        # the respond to block of code, handles the AJAX requests
        respond_to do |format|
          # the partial expects a _stock_data.js.erb file under the views/users folder
          format.js { render partial: 'users/stock_data' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Symbol not found: #{params[:stock]}"
          format.js { render partial: 'users/stock_data' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Symbol can't be empty"
        format.js { render partial: 'users/stock_data' }
      end
    end

  end


end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.get_stock_from_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "Stock #{stock.ticker} removed from tacking"
    redirect_to  my_portfolio_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @tracked_stocks = current_user.stocks
  end

  def comrades
    @comrades = current_user.comrades
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comrades/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @comrades.each do |comrade| %>
          <tr>
            <td><%= comrade.email %></td>
            <td><%= comrade.first_name %></td>
            <td><%= comrade.last_name %></td>
            <td><%= link_to 'Stop Following', '#',
                            data: {confirm: "Are you sure?"}, class: 'btn btn-warning'%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class='alert alert-success'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class='alert alert-danger'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Stock Tracker', root_path, class: "navbar-brand" %>
    <% if current_user %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item <%= "active" if request.path == my_portfolio_path %>">
            <%= link_to 'My Portfolio', my_portfolio_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Comrades', comrades_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item d-inline p-2 bg-primary text-white px-2">
            <%= fa_icon 'user'%> <%=link_to current_user.full_name, edit_user_registration_path, class: "text-white" %>
          </li>
          <li class="nav-item px-2">
            <%= link_to 'Sign Out', destroy_user_session_path, class: "btn btn-danger logout-button", method: :delete  %>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStockTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<!--    This stylesheet_link_tag is referencing to the app/assets/stylesheets/application.css file-->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<!--    This javascript_pack_tag is referring to the app/assets/javascript/pack/application.js file-->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container-fluid">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_stock_table.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <th scope="col">Ticker</th>
        <th scope="col">Company Name</th>
        <th scope="col">Price</th>
        <th scope="col">Actions</th>
      </tr>
      </thead>
      <tbody>
      <%= @tracked_stocks.each do |stock| %>
        <tr>
          <th scope="row"><%= stock.ticker %></th>
          <td><%= stock.name %></td>
          <td><%= stock.last_price %></td>
          <td><%= link_to 'Remove' , user_stock_path(stock), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-warning' %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_stock_data.html.erb
<div class="col-sm-3 mt-2">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
  <div class="card card-header">
    <p>
      <strong>Symbol: </strong><%= @stock.ticker %>
    </p>
    <p>
      <strong>Company Name: </strong><%= @stock.name %>
    </p>
    <p>
      <strong>Last Price: </strong><%= @stock.last_price %>
    </p>

    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-xs btn-success", method: :post %>
    <% else %>
      <span>
        You are already tracking
        <% if !current_user.under_stock_limit? %>
          10 stocks
        <% else current_user.stock_already_tracked? @stock.ticker %>
          <%= @stock.ticker %>
        <% end %>
      </span>
    <% end %>

  </div>
<% end %>

app/views/users/_stock_data.js.erb
//The below query will grab the <div> block with the id="stock_data_div_block" from the DOM.
//In our case the specified id is in the _stock_data.html.erb
// you need to escape the JavaScript, not really sure why(something related with embedded ruby).
//to escape java, we have escape_javascript() method or we can simply use the 'j' alias: '<%#= j render 'users/stock_data' %>'
// if you don't specify that is a .html file it will enter an infinity loop, because the current .js file has the same name
document.querySelector('#stock_data_div_block').innerHTML = '<%= escape_javascript(render 'users/stock_data.html') %>'

app/views/users/comrades.html.erb
<h1>Comrades</h1>


<% unless @comrades.empty? %>
  <%=  render 'comrades/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>
<div class="search-area">
  <h3>Search Stocks</h3>
  <!--  form_tag is accepting as parameters the route where you want to send the form, and what verb will be used-->
<!--  adding 'remote: true'  is transforming the form requests into an AJAX request-->
  <%= form_tag search_stock_path, remote: true, method: :get  do%>
    <div class="form-group row">
      <div class="col-sm-3">
<!--        this text_field_tag will save the value in the :stock variable which will be sent through the params.
            Then we want to retrieve that value from the params, using the key :stock-->
        <%= text_field_tag :stock, params[:stock], placeholder: "Ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="stock_data_div_block">

</div>
<br>
<%= render 'stocks/stock_table' %>

app/views/welcome/index.html.erb
<h1>Welcome to Stock Tracker</h1>

<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>